MMORPG/MMORPG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('advert_app.urls')),
    path('sign/', include('sign_app.urls')),
    path('account/', include('allauth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMORPG/advert_app/urls.py
from django.urls import path
from .views import (
    PostList, PostCreateView, PostDetail, CommentToPost, accept_comment, delete_comment
    )


urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('create/', PostCreateView.as_view(), name='create_post'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('comment/<int:pk>', CommentToPost.as_view(), name='write_comment'),
    path('accept/<int:id_comment>', accept_comment, name='accept_comment'),
    path('delete_comment/<int:id_comment>', delete_comment, name='delete_comment')
]

MMORPG/sign_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(), name='signup')
]

MMORPG/advert_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import redirect


class Post(models.Model):
    """
    Модель для создания объявлений
    """
    tank = 'TN'  # танк
    heal = 'HL'  # хил
    damage_dealer = 'DD'  # дамагер
    trader = 'TR'  # торговец
    guild_master = 'GM'  # гилдмастер
    questgiver = 'QG'  # квестгивер
    blacksmith = 'BS'  # кузнец
    tanner = 'TN'  # кожевник
    poison_master = 'PM'  # зельевар
    spell_master = 'SM'  # мастер заклинаний

    SELECT = [
        (tank, 'Tанк'),
        (heal, 'Хил'),
        (damage_dealer, 'Дамагер'),
        (trader, 'Торговец'),
        (guild_master, 'Гилдмастер'),
        (questgiver, 'Квестгивер'),
        (blacksmith, 'Кузнец'),
        (tanner, 'Кожевник'),
        (poison_master, 'Зельевар'),
        (spell_master, 'Мастер заклинаний')
    ]

    post_title = models.CharField(max_length=250, default='Заголовок объявления', unique=True)
    post_text = models.TextField(default='Введите текст объявления')
    post_author = models.ForeignKey('Author', on_delete=models.CASCADE)
    post_category = models.CharField(max_length=2, choices=SELECT)
    post_image = models.ImageField(upload_to='images/', blank=True, null=True)
    post_time_in = models.DateTimeField(auto_now_add=True,)
    post_rating = models.IntegerField(default=0,)

    def __str__(self):
        return f'{self.post_title} {self.post_author}'

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Comment(models.Model):
    """    Модель для создания откликов к объявлениям
    """
    comment_text = models.TextField(blank=True)
    comment_time_in = models.DateTimeField(auto_now_add=True)
    comment_to_post = models.ForeignKey('Post', on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_status = models.IntegerField(blank=True, null=True)  # для статуса отклика - для принятия или удаления


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.IntegerField(default=0)

    def update_rating(self):
        sum_author_rating = Post.objects.filter(post_author=self.id).values('post_rating')
        self.author_rating = sum([i['post_rating'] for i in sum_author_rating])

    def __str__(self):
        return f'{self.author}'

MMORPG/sign_app/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

MMORPG/advert_app/forms.py
from django import forms
from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['post_title'].label = 'Заголовок'
    #     self.fields['post_category'].label = 'Категория'

    class Meta:
        model = Post
        fields = ['post_title', 'post_text', 'post_author', 'post_category', 'post_image']


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

MMORPG/advert_app/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView

from .models import Post, Author, Comment
from .forms import PostCreateForm, CommentCreateForm
from django.contrib.auth.models import User


class PostList(ListView):
    model = Post
    ordering = 'post_time_in'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = [i['comment_to_post_id'] for i in Comment.objects.all().values('comment_to_post_id')]
        if self.request.user.username in [i['author__username'] for i in Author.objects.all().values('author__username')]:
            context['author'] = Author.objects.get(author__username=self.request.user.username)
        context['is_author'] = self.request.user.username in [i['author__username'] for i in Author.objects.all().values('author__username')]
        return context


class PostCreateView(CreateView):  # модель для создания новостей
    form_class = PostCreateForm
    model = Post
    template_name = 'post_create.html'


class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(comment_to_post_id=self.kwargs['pk'])
        # создаем список существующих авторов и проверяем есть пользователь среди них
        list_authors = [i['author__username'] for i in Author.objects.all().values('author__username')]
        if self.request.user.username in list_authors:
            context['author'] = Author.objects.get(author__username=self.request.user.username)
        context['is_author'] = self.request.user.username in [i['author__username'] for i in
                                                              Author.objects.all().values('author__username')]
        return context


class CommentToPost(CreateView):
    form_class = CommentCreateForm
    model = Comment
    template_name = 'comment.html'
    success_url = '/posts/'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.comment_to_post = Post.objects.get(id=self.kwargs['pk'])
        comment.comment_author = User.objects.get(id=self.request.user.id)
        comment.comment_status = 0
        return super().form_valid(form)


def accept_comment(request, id_comment):  # принятие комментариев присваивая им статус = 1
    comment = Comment.objects.get(id=id_comment)
    comment.comment_status = 1
    comment.save()
    comment_id = Comment.objects.get(id=id_comment)
    return redirect(f'/posts/{comment_id.comment_to_post_id}')


def delete_comment(request, id_comment):  # удаление комментариев к посту
    comment = Comment.objects.get(id=id_comment)
    Comment.objects.get(id=id_comment).delete()
    return redirect(f'/posts/{comment.comment_to_post_id}')

MMORPG/sign_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from .models import BaseRegisterForm


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = 'posts/'
    template_name = 'sign/signup.html'

MMORPG/templates/comment.html
{% extends 'flatpages/default.html' %}

{% block title %}
Create comment
{% endblock title %}

{% block content %}
<h1>Написать отзыв пост</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Отправить" class="send-post">
</form>
<hr>
{% endblock content %}

MMORPG/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block title %}
Create post
{% endblock title %}

{% block content %}
<h1>Создать пост</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Сохранить" class="send-post">
</form>
<hr>
{% endblock content %}

MMORPG/templates/post_detail.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<div>
	<table class="table-background">
		<tr>
			<th class="table-frame-title-th">Заголовок:</th>
			<td class="table-frame-title">{{ post.post_title }}</td>
		</tr>
		<tr>
			<th class="table-frame-title-th">Текст поста:</th>
			<td class="table-frame-title">{{ post.post_text }}</td>
		</tr>
		<tr>
			<th class="table-frame-title-th">Изображение</th>
			{% if post.post_image %}
				<td><img src="/media/{{ post.post_image }}" class="image-picture-post"></td>
			{% else %}
				<td>Нет изображения</td>
			{% endif %}
		</tr>
		<tr>
			<th class="table-frame-title-th">Категория:</th>
			<td class="table-frame-title">{{ post.get_post_category_display }}</td>
		</tr>
		<tr>
			<th class="table-frame-title-th">Автор:</th>
			<td class="table-frame-title">{{ post.post_author }}</td>
		</tr>
		<tr>
			<th class="table-frame-title-th">Коментарии:</th>

			<td class="frame-comment-li">
				<ul class="list-comment-ul">
					{% for comment in comments %}
						<li>
							<span class="frame-comment">{{ comment.comment_text }}</span> <i>комментарий оставил:</i> <b>{{ comment.comment_author }}</b>

							<!-- Кнопки принять или удалить коментарий только если вы автор поста -->
							{% if post.post_author == author %}
								{% if comment.comment_status != 1 %}
									<a href="{% url 'accept_comment' id_comment=comment.pk %}"><button>Принять</button></a>
									<a href="{% url 'delete_comment' id_comment=comment.pk %}"><button>Удалить</button></a>
								{% else %}
									<span class="accepted_comment">комментарий принят!!!</span>
								{% endif %}
							{% endif %}
							<!-- Конец блока кнопок -->

						</li>
					{% endfor %}
					Всего коментариев: {{ comments|length }}
				</ul>
			</td>
		</tr>
	</table>
</div>
{% endblock content %}

MMORPG/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <div class="div-posts">
        <table class="table-background">
            {% for post in posts %}
                <tr>
                    <th class="table-frame-title-th">Заголовок:</th>
                    <td class="table-frame-title"><b>{{post.post_title}}<button class="read-button"><a href="{% url 'post_detail' pk=post.pk %}" class="link-button">Читать</a></button></b></td>
                </tr>
                <tr>
                    <th class="table-frame-title-th">Текст:</th>
                    <td class="table-frame-title">{{post.post_text}}</td>
                </tr>
                <tr>
                    <th class="table-frame-title-th">Изображение:</th>
                    {% if post.post_image %}
                        <td><img src="/media/{{post.post_image}}" class="image-picture-post"></td>
                    {% else %}
                        <td class="table-frame-title">Нет изображения</td>
                    {% endif %}
                </tr>
                <tr>
                    <th class="table-frame-title-th">Категория:</th>
                    <td class="table-frame-title-2">{{post.get_post_category_display}}</td>
                </tr>
                <tr>
                    <th class="table-frame-title-th">Автор:</th>
                    <td class="table-frame-title-2">{{ post.post_author }}</td>
                </tr>
                <tr>
                    <th class="table-frame-title-th">Комментарии:</th>
                    <td>
                        {% if post.id not in comments %}
                            <span class="table-frame-title-2">нет коментариев</span>
                        {% else %}
                            <span class="exist-comment">есть коментарии</span>     
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <td>
                        {% if post.post_author == author %}
                            Это ваша статья!!!
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td align="center">
                        <div class="button-div">
                            <a class="like-button" href=""><img src="{% static 'img/like.png' %}"></a>
                            <a class="dislike-button"><img src="{% static 'img/dislike.png' %}"></a>
                            <a href="{% url 'write_comment' pk=post.pk %}" class="comment-button"><button class="comment-button-1">Оставить отзыв</button></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <th><hr class="post-line-hr"></th>
                </tr>
            {% endfor %}
        </table>

        <!-- блок пагинации -->
        <div class="pagination-pages">
            {% if page_obj.has_previous %}
                <a href="?page=1">1</a>
                {% if page_obj.previous_page_number != 1 %}
                    ...
                    <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                {% endif %}
            {% endif %}

            {{ page_obj.number }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                {% if paginator.num_pages != page_obj.next_page_number %}
                    ...
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            {% endif %}
        </div>
        <!-- конец блока пагинации -->

    </div>
{% endblock content %}

MMORPG/templates/sign/login.html
{% extends 'account/welcome.html' %}

{% block title %}
SignIn
{% endblock title %}

{% block content %}
    <h2>Войти в систему</h2>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
        <input type="submit" value="Войти">
    </form>
{% endblock content %}

MMORPG/templates/sign/logout.html
{% extends 'account/welcome.html' %}

{% block title %}
Exit
{% endblock title %}

{% block content %}
    <h1>Вы вышли из системы</h1>
{% endblock content %}

MMORPG/templates/sign/signup.html
{% extends 'account/welcome.html' %}

{% block title %}
SignUp
{% endblock title %}

{% block content %}
    <h2>Регистрация</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Продолжить">
    </form>
{% endblock content %}